<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository;

use Customize\Entity\Sample;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * SampleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SampleRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Sample::class);
    }

    /**
 * ’Ç‰Á
 *
 * @paramu string $sample_column01
 * 
 */
    public function customAdd($title){
    
        if(empty($title)){
            return false;
        }
        $Sample = new Sample();
        $Sample->setTitle($title);


        $em = $this->getEntityManager();
        $em->persist($Sample);
        $em->flush($Sample);
        
        return true;
    }
}